services:
  redis:
    image: redis:latest
    container_name: rng-redis
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  app_network:
    driver: bridge
