services:
  app:
    build: .
    container_name: rng-back
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - LOG_FILE=/app/logs/app.log
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
