services:
  app:
    image: ghcr.io/topnik073/rng-404:latest
    container_name: rng-back
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - LOG_FILE=/app/logs/app.log
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app_dir/logs
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: rng-redis
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  app_network:
    driver: bridge
